# NumPy

NumPy stands for Numerical Python. It is very useful library. The data structure provided by this library is arrays of any dimensions as well as matrices. Arrays are nothing but collection of homogeneous elements.

In [1]:
import numpy as np

In [3]:
a = np.array([1, 2, 3.4])
a

array([1. , 2. , 3.4])

**Remark:** We've got the array of 1 dimension and it has upcasted the data type of elements of this array into float type and all the elements are of float type. Also, this array is homogeneous.

In [4]:
type(a)

numpy.ndarray

In [2]:
# To get array of any dimensions
np.array([[4, 5, 6], [6, 7, 8]], ndmin = 6)

array([[[[[[4, 5, 6],
           [6, 7, 8]]]]]])

In [5]:
# To convert any array into higher number of dimensions
np.array([1, 2, 3.4], ndmin = 3)

array([[[1. , 2. , 3.4]]])

In [4]:
# We can have list of tuples or list of list while defining the numpy array. We'll get the same output.
np.array([(2, 3), (4, 5)])

array([[2, 3],
       [4, 5]])

In [7]:
b = np.array([[2, 3], [4, 5]])
b

array([[2, 3],
       [4, 5]])

In [8]:
type(b)

numpy.ndarray

In [9]:
# To know the dimensions of the array
b.ndim

2

In [12]:
# indexing in arrays
b[0][0]

2

In [16]:
b[0]

array([2, 3])

In [3]:
# typecasting in numpy
np.array([8, 9, 4.5], dtype = complex)

array([8. +0.j, 9. +0.j, 4.5+0.j])

In [15]:
# We have passed list of the tuples as the input for defining the array
# We can define data type of elements in an array.
# Here, it'll represent 23 & 89 by 'a' and 45 & 32 by 'b'. It'll assign data type as i2 to all the elements represented by 'a'.
# It'll assign data type as i4 to all the elements represented by 'b'.
# i2: int 16
# i4: int 32
# i8: int 64
x = np.array([(23, 45), (89, 32)], dtype = ([('a', '<i2'), ('b', '<i4')]))
x

array([(23, 45), (89, 32)], dtype=[('a', '<i2'), ('b', '<i4')])

In [18]:
x[0]

(23, 45)

In [19]:
type(x[0])

numpy.void

In [20]:
x[0][0]

23

In [21]:
type(x[0][0])

numpy.int16

In [23]:
x[0][1]

45

In [24]:
type(x[0][1])

numpy.int32

In [26]:
y = np.mat([(23, 45), (89, 32)])
y

matrix([[23, 45],
        [89, 32]])

In [27]:
type(y)

numpy.matrix

**Remark** np.matrix is the subclass of np.array.

In [33]:
np.issubclass_(np.matrix, np.ndarray)

True

In [34]:
# Another way to do the same thing
issubclass(np.matrix, np.ndarray)

True

In [29]:
# To convert any other data structure in the form of array we can use np.asarray as well apart from np.array.
# It is same as np.array. The difference is just only in the parameters that are available in their respective definitions.
np.asarray([[1, 2, 3], [2, 3, -9], [8, 9, 1]])

array([[ 1,  2,  3],
       [ 2,  3, -9],
       [ 8,  9,  1]])

In [31]:
# We can control the data type of elements of an array by using the parameter called dtype
np.asarray([[1, 2, 3], [2, 3, -9], [8, 9, 1]], dtype = 'int8')

array([[ 1,  2,  3],
       [ 2,  3, -9],
       [ 8,  9,  1]], dtype=int8)

# np.asanyarray

This would help in converting non array data structes into array but it'll not convert the variant of array like matrix into an array. While np.array and np.asarray both can convert the non array data structures as well as any variant of array like matrix into an array.

In [35]:
m = [(2, 3), (6, 7), (9, 0), (-4, 2)]
m

[(2, 3), (6, 7), (9, 0), (-4, 2)]

In [36]:
type(m)

list

In [37]:
type(np.array(m))

numpy.ndarray

In [38]:
type(np.asarray(m))

numpy.ndarray

In [39]:
type(np.asanyarray(m))

numpy.ndarray

In [42]:
n = np.matrix(m)

In [43]:
type(n)

numpy.matrix

In [45]:
type(np.asanyarray(n))

numpy.matrix

**Remark:** np.array, np.asarray, and np.asanyarray all will help in converting any data structure into array but np.asanyarray wouldn't convert matrix into an array.

**deep copy:** If we are defining a variable let's say x and defining the expression y = np.copy(x) then this is known as creating a deep copy of the variable x. In this case, both x and y would point towards different locations and whatever changes we'll make in either x or y those would not be reflected in other variable. That means if we'll make any changes in x then Y would not change and vice versa.

**Shallow copy:** If we are defining a variable let's say x and defining the expression y = x then this is known as creating a shallow copy of the variable x. In this case, both x and y would point towards same location and whatever changes we'll make in either x or y those would be reflected in both y & x.

# np.fromfunction()

It tries to calculate all the elements of an array with the help of execution of function over each coordinate.

In [49]:
np.fromfunction(lambda x, y: x == y* 3, (2, 3))

array([[ True, False, False],
       [False, False, False]])

In [52]:
np.fromfunction(lambda i, j: i ** j, (3, 3), dtype=int)

array([[1, 0, 0],
       [1, 1, 1],
       [1, 2, 4]], dtype=int32)

In [54]:
l1 = np.fromfunction(lambda i, j, k: i + j + k, (3, 3, 3), dtype = int)
l1

array([[[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4]],

       [[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]],

       [[2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]]])

In [59]:
np.ndim(l1)

3

In [61]:
l2 = np.fromfunction(lambda i, j, k, l: i + j + k + l, (2, 3, 3, 3), dtype = int)
l2

array([[[[0, 1, 2],
         [1, 2, 3],
         [2, 3, 4]],

        [[1, 2, 3],
         [2, 3, 4],
         [3, 4, 5]],

        [[2, 3, 4],
         [3, 4, 5],
         [4, 5, 6]]],


       [[[1, 2, 3],
         [2, 3, 4],
         [3, 4, 5]],

        [[2, 3, 4],
         [3, 4, 5],
         [4, 5, 6]],

        [[3, 4, 5],
         [4, 5, 6],
         [5, 6, 7]]]])

In [62]:
np.ndim(l2)

4

In [63]:
l3 = np.fromfunction(lambda i, j, k, l, m: i + j + k + l + m, (2, 3, 3, 3, 3), dtype = int)
l3

array([[[[[0, 1, 2],
          [1, 2, 3],
          [2, 3, 4]],

         [[1, 2, 3],
          [2, 3, 4],
          [3, 4, 5]],

         [[2, 3, 4],
          [3, 4, 5],
          [4, 5, 6]]],


        [[[1, 2, 3],
          [2, 3, 4],
          [3, 4, 5]],

         [[2, 3, 4],
          [3, 4, 5],
          [4, 5, 6]],

         [[3, 4, 5],
          [4, 5, 6],
          [5, 6, 7]]],


        [[[2, 3, 4],
          [3, 4, 5],
          [4, 5, 6]],

         [[3, 4, 5],
          [4, 5, 6],
          [5, 6, 7]],

         [[4, 5, 6],
          [5, 6, 7],
          [6, 7, 8]]]],



       [[[[1, 2, 3],
          [2, 3, 4],
          [3, 4, 5]],

         [[2, 3, 4],
          [3, 4, 5],
          [4, 5, 6]],

         [[3, 4, 5],
          [4, 5, 6],
          [5, 6, 7]]],


        [[[2, 3, 4],
          [3, 4, 5],
          [4, 5, 6]],

         [[3, 4, 5],
          [4, 5, 6],
          [5, 6, 7]],

         [[4, 5, 6],
          [5, 6, 7],
          [6, 7, 8]]],


        [[[3,

In [64]:
np.ndim(l3)

5

In [65]:
# It's dimension would be 6. We'll get to know this by the total number of elements we have provided in a tuple separated by 
# commas like (7, 6, 5, 4, 3, 2)
l4 = np.fromfunction(lambda i, j, k, l, m, n: i + j + k + l + m + n, (7, 6, 5, 4, 3, 2), dtype = int)
l4

array([[[[[[ 0,  1],
           [ 1,  2],
           [ 2,  3]],

          [[ 1,  2],
           [ 2,  3],
           [ 3,  4]],

          [[ 2,  3],
           [ 3,  4],
           [ 4,  5]],

          [[ 3,  4],
           [ 4,  5],
           [ 5,  6]]],


         [[[ 1,  2],
           [ 2,  3],
           [ 3,  4]],

          [[ 2,  3],
           [ 3,  4],
           [ 4,  5]],

          [[ 3,  4],
           [ 4,  5],
           [ 5,  6]],

          [[ 4,  5],
           [ 5,  6],
           [ 6,  7]]],


         [[[ 2,  3],
           [ 3,  4],
           [ 4,  5]],

          [[ 3,  4],
           [ 4,  5],
           [ 5,  6]],

          [[ 4,  5],
           [ 5,  6],
           [ 6,  7]],

          [[ 5,  6],
           [ 6,  7],
           [ 7,  8]]],


         [[[ 3,  4],
           [ 4,  5],
           [ 5,  6]],

          [[ 4,  5],
           [ 5,  6],
           [ 6,  7]],

          [[ 5,  6],
           [ 6,  7],
           [ 7,  8]],

          [[ 6,  7]

In [66]:
np.ndim(l4)

6

In [68]:
list(range(3, 8))

[3, 4, 5, 6, 7]

In [69]:
list(range(3, 8, 2))

[3, 5, 7]

In [70]:
np.arange(3, 8)

array([3, 4, 5, 6, 7])

In [71]:
np.arange(3, 8, 2)

array([3, 5, 7])

range(start, end, step size)

np.arange(start, end, step size)

np.linspace(start, end, number of data points, endpoint)

linspace returns those many data points as you've mentioned but those would be equally spaced and with in the range i.e. start till end.

1. range function is available in base python while arange function is available in numpy package.
2. the parameters start, end, and step size can take integer or float value in case of arange function while the parameters start, end, and step size can take only integer value in case of range function.
3. There is one parameter available in linspace i.e. endpoint. By default it's True. We can make it False as well. Also, this parameter is not available in case of range and arange functions.
4. By default starting and ending points are not included in range & arange functions but this is not the case with linspace. in linspace function by default end point is included.
5. The data type of the output of the range function is integer alaways. The data type of the output of the arange function can be integer as well as float. The data type of the output of the linspace function is float alaways.

list(range(3, 8, 0.5)) This is incorrect.

In [74]:
np.arange(3, 8, 0.5)

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5])

In [75]:
np.linspace(3, 8, 20)

array([3.        , 3.26315789, 3.52631579, 3.78947368, 4.05263158,
       4.31578947, 4.57894737, 4.84210526, 5.10526316, 5.36842105,
       5.63157895, 5.89473684, 6.15789474, 6.42105263, 6.68421053,
       6.94736842, 7.21052632, 7.47368421, 7.73684211, 8.        ])

In [76]:
np.linspace(3, 8, 20, endpoint=False)

array([3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  , 5.25, 5.5 ,
       5.75, 6.  , 6.25, 6.5 , 6.75, 7.  , 7.25, 7.5 , 7.75])

In [50]:
# It'll create a 2D array with 50 data points each b/w 2 to 10 and 4 to 10
np.linspace([2, 4], 10)

array([[ 2.        ,  4.        ],
       [ 2.16326531,  4.12244898],
       [ 2.32653061,  4.24489796],
       [ 2.48979592,  4.36734694],
       [ 2.65306122,  4.48979592],
       [ 2.81632653,  4.6122449 ],
       [ 2.97959184,  4.73469388],
       [ 3.14285714,  4.85714286],
       [ 3.30612245,  4.97959184],
       [ 3.46938776,  5.10204082],
       [ 3.63265306,  5.2244898 ],
       [ 3.79591837,  5.34693878],
       [ 3.95918367,  5.46938776],
       [ 4.12244898,  5.59183673],
       [ 4.28571429,  5.71428571],
       [ 4.44897959,  5.83673469],
       [ 4.6122449 ,  5.95918367],
       [ 4.7755102 ,  6.08163265],
       [ 4.93877551,  6.20408163],
       [ 5.10204082,  6.32653061],
       [ 5.26530612,  6.44897959],
       [ 5.42857143,  6.57142857],
       [ 5.59183673,  6.69387755],
       [ 5.75510204,  6.81632653],
       [ 5.91836735,  6.93877551],
       [ 6.08163265,  7.06122449],
       [ 6.24489796,  7.18367347],
       [ 6.40816327,  7.30612245],
       [ 6.57142857,

In [51]:
# It'll transpose the data
np.linspace([2, 4], 10, axis = 1)

array([[ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
         2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
         3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
         4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
         5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
         6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
         6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
         7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
         8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
         9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ],
       [ 4.        ,  4.12244898,  4.24489796,  4.36734694,  4.48979592,
         4.6122449 ,  4.73469388,  4.85714286,  4.97959184,  5.10204082,
         5.2244898 ,  5.34693878,  5.46938776,  5.59183673,  5.71428571,
         5.83673469,  5.95918367,  6.08163265,  6.

In [78]:
np.arange(3, 8, 2)

array([3, 5, 7])

In [79]:
np.linspace(3, 8, 2)

array([3., 8.])

In [80]:
np.logspace(2, 7, num = 4)

array([1.00000000e+02, 4.64158883e+03, 2.15443469e+05, 1.00000000e+07])

In [81]:
np.logspace(2, 7, num = 4, base = 2.0)

array([  4.        ,  12.69920842,  40.3174736 , 128.        ])

In [86]:
np.zeros((3, 4, 8))

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]]])

In [87]:
np.zeros((3, 4, 8)) + 5

array([[[5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5.]],

       [[5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5.]],

       [[5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5.]]])

In [88]:
np.zeros((3, 4, 8)) * 2

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]]])

In [89]:
np.zeros((3, 4, 8)) + 5 * 2

array([[[10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.]],

       [[10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.]],

       [[10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.]]])

In [106]:
(np.zeros((3, 4, 8)) + 5) * 2

array([[[10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.]],

       [[10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.]],

       [[10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.]]])

In [90]:
np.linspace(4, 8, 80)

array([4.        , 4.05063291, 4.10126582, 4.15189873, 4.20253165,
       4.25316456, 4.30379747, 4.35443038, 4.40506329, 4.4556962 ,
       4.50632911, 4.55696203, 4.60759494, 4.65822785, 4.70886076,
       4.75949367, 4.81012658, 4.86075949, 4.91139241, 4.96202532,
       5.01265823, 5.06329114, 5.11392405, 5.16455696, 5.21518987,
       5.26582278, 5.3164557 , 5.36708861, 5.41772152, 5.46835443,
       5.51898734, 5.56962025, 5.62025316, 5.67088608, 5.72151899,
       5.7721519 , 5.82278481, 5.87341772, 5.92405063, 5.97468354,
       6.02531646, 6.07594937, 6.12658228, 6.17721519, 6.2278481 ,
       6.27848101, 6.32911392, 6.37974684, 6.43037975, 6.48101266,
       6.53164557, 6.58227848, 6.63291139, 6.6835443 , 6.73417722,
       6.78481013, 6.83544304, 6.88607595, 6.93670886, 6.98734177,
       7.03797468, 7.08860759, 7.13924051, 7.18987342, 7.24050633,
       7.29113924, 7.34177215, 7.39240506, 7.44303797, 7.49367089,
       7.5443038 , 7.59493671, 7.64556962, 7.69620253, 7.74683

In [91]:
np.matrix([[3, 4, 6], [7, 8, 9.4]])

matrix([[3. , 4. , 6. ],
        [7. , 8. , 9.4]])

In [94]:
x = np.ones((4, 5, 2))
x

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [95]:
np.ndim(x)

3

In [96]:
x.size

40

In [97]:
x.shape

(4, 5, 2)

In [98]:
x.dtype

dtype('float64')

In [100]:
y = np.ones((4, 5, 2))
y

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [101]:
np.ndim(y)

3

In [102]:
y.size

40

In [103]:
y.shape

(4, 5, 2)

In [104]:
y.dtype

dtype('float64')

In [105]:
x1 = np.ones((3, 3, 3))
x2 = np.zeros((3, 3, 3))
x1+x2

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [110]:
z = np.arange(16)
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [111]:
z.ndim

1

In [112]:
z.shape

(16,)

reshape() will reshape the array in such a way that size of the array or total number of elements in the array would remain same. Let's say there is an array with 12 elements then there could be multiple combinations that would end up in giving 12 elements like (4, 3), (3, 4), (12, 1), (1, 12), (2, 6), (6, 2), (3, 4, 1), (12, 1, 1), etc.

There is one more functionality which is available. Consider the above example. We can use any negative number as one of the values of the parameters of the shape like (-1, 4), (6, -343), etc. Here, -1 would be 3 in first case and -343 would be 2 in second case. Program needs to return an array with total number of elements as 12 and one of the values of the shape parameters we're giving so accordingly it'll calculate the value corresponding to any negative number and assign the same. The negative number is representing unknown dimension. There could be only one negative value at one point in time.

In [113]:
z.reshape(16, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [114]:
# since total number of elements must be 16 and we've given one of the values as 2 so another value would be 8 for sure
z.reshape(-1, 2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [115]:
z.reshape(-3456, 2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [52]:
np.random.randint(10, 100, 2)

array([12, 60])

In [53]:
np.random.randint(10, 100, [3, 4])

array([[30, 25, 51, 45],
       [48, 81, 30, 41],
       [70, 20, 89, 87]])

In [56]:
# to get the same random number, we can use
np.random.seed(13)
np.random.randint(10, 100, 2)

array([92, 58])

To get the diagonal elements of any matrix we can use diag(). If the array is not in the format of square matrix then it would give the diagonal elements from the very first square matrix of maximum size that is possible.

np.diag(array1, k) where array1 could be any array and k can take int value. By default k = 0 that means this function will return the array comprising of main diagonal. k = 1 means diagonal above the main diagonal. k = -1 means diagonal below the main diagonal.

In [121]:
array1 = np.array([[1, 2], [6, -8], [5, 0]])
array1

array([[ 1,  2],
       [ 6, -8],
       [ 5,  0]])

In [122]:
np.diag(array1) # By default k = 0

array([ 1, -8])

In [123]:
np.diag(array1, k = 1) # We'll get the value above the main diagonal

array([2])

In [124]:
np.diag(array1, k = -1) # We'll get the diagonal values below the main diagonal

array([6, 0])

In [125]:
np.diag(array1, k = -2)

array([5])

In [130]:
x1 = np.arange(16).reshape((-1, 8))
x1

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [131]:
np.diag(x1, k = 0)

array([0, 9])

In [132]:
np.diag(x1, k = 1)

array([ 1, 10])

In [133]:
np.diag(x1, k = -1)

array([8])

In [135]:
np.diag(x1, k = 6)

array([ 6, 15])

In [136]:
np.diag(x1, k = 7)

array([7])

In [137]:
np.diag(x1, k = -2) # Since there is no element

array([], dtype=int32)

In [140]:
array1

array([[ 1,  2],
       [ 6, -8],
       [ 5,  0]])

In [139]:
# It'll create a square matrix using the diagonal elements and place them on the doagonal and rest of the elements would be 
# zero in the square matrix
np.diag(np.diag(array1))

array([[ 1,  0],
       [ 0, -8]])

In [143]:
# Here, we are creating an array of size 16 and reshaping it to (4, 4). Finding the diagonal elements and using them creating 
# a square matrix by placing these diagonal elements at the diagonal respectively and put zeros at the rest of the places.
np.diag(np.diag(np.arange(16).reshape(4, 4)))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [4]:
# It'll put all the elelements in one container and put them in diagonal and place 0 at rest of the places
np.diagflat([[1, [2, 4], 3], [4, 5, 6]])

array([[1, 0, 0, 0, 0, 0],
       [0, list([2, 4]), 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]], dtype=object)

In [5]:
# np.tri(num of rows, num of columns, value of k). It'll consider the value of k and specify the diagonal. All the values below
# that diagonal would be 1 and rest of the values would be zero.
np.tri(4,5, 0)

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.]])

In [6]:
z = np.array(([1, 2, 3], [4, 5, 6], [7, 8, 9]))
z

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
# To get the lower traingle of an array. Here, all the elements would be zero above the main diagonal.
np.tril(z)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [8]:
# To get the upper traingle of an array. Here, all the elements would be zero below the main diagonal.
np.triu(z)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [9]:
# By default k = 0. If we choose k = 1 then all the elements above the diagonal corresponding to k = 1 would be 0.
np.tril(z, k = 1)

array([[1, 2, 0],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
# By default k = 0. If we choose k = 1 then all the elements below the diagonal corresponding to k = 1 would be 0.
np.triu(z, k = 1)

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0]])

In [11]:
# We need to mention the shape of the array.
# rand would generate the random numbers b/w 0 and 1 which'll follow uniform distribution.
np.random.rand(3, 4)

array([[0.85637223, 0.83912446, 0.13084986, 0.92130759],
       [0.86542536, 0.26089776, 0.63672202, 0.80536529],
       [0.45753493, 0.90920637, 0.95575465, 0.85147466]])

In [12]:
# We need to mention the shape of the array.
# randn would generate a sample from standard normal distribution where mean = 0 and std = 1
np.random.randn(3, 4)

array([[-1.67958277, -0.72698384, -0.72040569,  1.08835825],
       [-0.31750514, -0.88392875,  0.19371171,  0.0569111 ],
       [ 1.46560011,  0.66519182,  0.81840632, -1.28889098]])

In [14]:
# We need to mention the range of numbers within which we want to see any random number.
# randint would generate random integer within the specified range
np.random.randint(3, 9)

6

In [15]:
# By default we'll receive single integer as the output. If we would like to generate multiple integers within the specified 
# range then we need to mention the number of integers we like to see in the output
np.random.randint(3, 9, 4)

array([5, 6, 8, 4])

In [16]:
# Here, we've provided the shape of the array i.e. (4, 5) and all the elements of this array would be an integer that would
# lie within the range 3 to 9. Upper bound of the range won't be included i.e. 9 won't be included.
np.random.randint(3, 9, (4, 5))

array([[3, 8, 5, 7, 8],
       [3, 4, 7, 5, 6],
       [5, 5, 6, 3, 3],
       [4, 3, 5, 8, 5]])

In [5]:
# To use the randint function, we're using a very big expression. In order to squeeze it, we can use
from numpy.random import randint as ri
ri(3, 9, (4, 5))

array([[4, 4, 4, 7, 5],
       [7, 7, 4, 3, 5],
       [5, 7, 8, 3, 7],
       [6, 3, 4, 7, 3]])

In [21]:
np.sort(ri(3, 9, (4, 5))) # Here, rows are sorted in ascending order by default

array([[4, 6, 7, 7, 7],
       [3, 4, 4, 5, 7],
       [3, 7, 7, 8, 8],
       [5, 6, 6, 7, 8]])

In [26]:
# To control the sorting row wise or column wise, we'll use axis parameter under np.sort
# axis = 1 means data movement in sorting would be done column wise
# axis = 0 means data movement in sorting would be done row wise
np.sort(ri(3, 9, (4, 5)), axis = 1)

array([[5, 6, 6, 7, 8],
       [4, 4, 6, 7, 7],
       [3, 5, 7, 8, 8],
       [3, 4, 8, 8, 8]])

In [28]:
z1 = ri(1, 100, (5, 6))
z1

array([[21, 27, 38, 81, 15, 69],
       [78, 86, 66, 91, 69,  3],
       [70, 50, 30, 37, 57, 60],
       [73, 19, 49, 95, 97, 94],
       [20, 78, 74, 19, 78, 20]])

In [29]:
np.max(z1)

97

In [30]:
np.min(z1)

3

In [31]:
# It'll return the index of maximum value in entire array
z1.argmax()

22

In [32]:
# Here, meaning of axis is opposite. We consider axis = 0 for rows but here we're considering the same for columns.
# axis = 1 means index of maximum value in a row
z1.argmax(axis = 1)

array([3, 3, 0, 4, 1], dtype=int64)

In [33]:
# axis = 0 means index of maximum value in a column
z1.argmax(axis = 0)

array([1, 1, 4, 3, 3, 3], dtype=int64)

In [53]:
x = np.array(range(2, 20, 2))
x

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [54]:
# To get the element at 5th index
x[4]

10

In [55]:
# To get the elements of an array in reverse order
x[-1::-1]

array([18, 16, 14, 12, 10,  8,  6,  4,  2])

In [58]:
# To get the last 5 elements
x[-1:-6:-1]

array([18, 16, 14, 12, 10])

In [61]:
# To get the 3rd, 6th & 8th element of an array
x[[3, 6, 8]]

array([ 8, 14, 18])

In [32]:
mat = ri(1, 100, (3, 5, 6))
mat

array([[[40, 67, 89,  2, 19, 62],
        [44, 95, 75, 13, 94, 28],
        [23, 34, 86, 90, 40, 82],
        [50, 49, 96, 41, 40, 72],
        [46, 17, 91,  2, 13, 59]],

       [[16, 42, 72, 53, 37, 61],
        [59, 37, 61, 65, 19, 71],
        [57, 10, 13,  6, 72, 32],
        [68, 99, 70, 54, 26, 73],
        [64, 18, 46, 58, 65, 68]],

       [[26, 99, 27, 58, 28, 51],
        [19, 76, 72, 11, 76, 90],
        [53, 56,  5, 24, 89, 69],
        [94, 83, 76, 24, 76, 21],
        [80, 37, 53, 31, 12, 63]]])

In [33]:
# To get the 2nd column from very first matrix
mat[0][:, 1]

array([67, 95, 34, 49, 17])

In [41]:
# To get the 2nd column from every matrix
mat[:, :, 1]

array([[67, 95, 34, 49, 17],
       [42, 37, 10, 99, 18],
       [99, 76, 56, 83, 37]])

In [42]:
# To get the first 2 rows from all the matrices together
mat[:, 0:2, :]

array([[[40, 67, 89,  2, 19, 62],
        [44, 95, 75, 13, 94, 28]],

       [[16, 42, 72, 53, 37, 61],
        [59, 37, 61, 65, 19, 71]],

       [[26, 99, 27, 58, 28, 51],
        [19, 76, 72, 11, 76, 90]]])

In [34]:
# Another wayout to do the same thing
mat[:, 0:2]

array([[[40, 67, 89,  2, 19, 62],
        [44, 95, 75, 13, 94, 28]],

       [[16, 42, 72, 53, 37, 61],
        [59, 37, 61, 65, 19, 71]],

       [[26, 99, 27, 58, 28, 51],
        [19, 76, 72, 11, 76, 90]]])

In [38]:
mat[0][:, 0:2]

array([[40, 67],
       [44, 95],
       [23, 34],
       [50, 49],
       [46, 17]])

In [40]:
# To extract the first 2 columns of each matrix
mat[:, :, 0:2]

array([[[40, 67],
        [44, 95],
        [23, 34],
        [50, 49],
        [46, 17]],

       [[16, 42],
        [59, 37],
        [57, 10],
        [68, 99],
        [64, 18]],

       [[26, 99],
        [19, 76],
        [53, 56],
        [94, 83],
        [80, 37]]])

In [43]:
# To get the last column of all the matrices
mat[:, :, -1]

array([[62, 28, 82, 72, 59],
       [61, 71, 32, 73, 68],
       [51, 90, 69, 21, 63]])

In [47]:
mat1 = np.array(np.random.randint(1000, 3000, (2, 3, 5, 4)))
mat1

array([[[[2682, 2982, 1136, 1500],
         [1973, 2593, 2223, 1156],
         [2481, 2489, 1832, 2063],
         [2638, 1676, 1208, 1942],
         [2402, 1434, 1323, 1901]],

        [[1889, 1555, 2406, 1994],
         [1438, 1820, 2375, 2596],
         [2049, 1269, 2707, 1814],
         [2480, 2267, 2692, 1670],
         [2662, 2819, 1156, 1226]],

        [[2171, 2801, 2271, 2016],
         [1098, 1784, 2038, 2584],
         [2067, 1130, 1150, 2108],
         [1688, 1369, 2845, 1270],
         [2668, 1120, 1947, 2942]]],


       [[[2677, 1416, 1741, 1236],
         [1447, 2187, 1739, 2459],
         [2379, 1195, 2892, 2624],
         [1732, 2736, 1097, 2951],
         [1572, 1186, 1197, 2339]],

        [[2436, 2328, 2939, 2693],
         [1083, 2877, 2397, 2187],
         [1162, 1007, 1335, 2907],
         [1963, 1909, 2509, 1920],
         [2642, 1563, 1765, 2697]],

        [[2277, 1436, 2824, 1030],
         [1520, 2202, 1584, 1553],
         [1639, 1511, 2618, 2980],
        

In [49]:
# To get the first two columns from all these matrices
mat1[:, :, :, 0:2]

array([[[[2682, 2982],
         [1973, 2593],
         [2481, 2489],
         [2638, 1676],
         [2402, 1434]],

        [[1889, 1555],
         [1438, 1820],
         [2049, 1269],
         [2480, 2267],
         [2662, 2819]],

        [[2171, 2801],
         [1098, 1784],
         [2067, 1130],
         [1688, 1369],
         [2668, 1120]]],


       [[[2677, 1416],
         [1447, 2187],
         [2379, 1195],
         [1732, 2736],
         [1572, 1186]],

        [[2436, 2328],
         [1083, 2877],
         [1162, 1007],
         [1963, 1909],
         [2642, 1563]],

        [[2277, 1436],
         [1520, 2202],
         [1639, 1511],
         [1757, 1334],
         [2151, 1093]]]])

**Remark:** To extract any elements from a ndarray, mention the name of the array. Put square brackets and then mention the indexes you want to extract as per the shape of the array like array has shape(2, 4, 5, 7, 9) that means array_name`[i1, i2, i3, i4, i5]` where i1 to i5 would let us know the element that needs to be captured from each axis like we want to extract very first column of all these matrices so syntax would be array_name`[:, :, :, :, 0]`. This can be generalized for arrays having any shape or dimension.

In [46]:
mat[mat > 50]

array([67, 89, 62, 95, 75, 94, 86, 90, 82, 96, 72, 91, 59, 72, 53, 61, 59,
       61, 65, 71, 57, 72, 68, 99, 70, 54, 73, 64, 58, 65, 68, 99, 58, 51,
       76, 72, 76, 90, 53, 56, 89, 69, 94, 83, 76, 76, 80, 53, 63])

In [6]:
mat1 = np.array(np.random.randint(1, 200, (4, 5)))
mat1

array([[ 34, 171, 188, 113,  45],
       [  1, 107, 120, 162,  74],
       [120,  92,   6,   4,  44],
       [128,  55,  74,  41, 189]])

In [7]:
# It's not same as matrix multiplication. It'll multiply corresponding elements with each other.
mat1 * mat1

array([[ 1156, 29241, 35344, 12769,  2025],
       [    1, 11449, 14400, 26244,  5476],
       [14400,  8464,    36,    16,  1936],
       [16384,  3025,  5476,  1681, 35721]])

In [11]:
mat2 = mat1[0:3, 0:3]
mat2

array([[ 34, 171, 188],
       [  1, 107, 120],
       [120,  92,   6]])

In [12]:
# For actual matrix multiplication use @
mat2@mat2

array([[23887, 41407, 28040],
       [14541, 22660, 13748],
       [ 4892, 30916, 33636]])

In [13]:
# It'll give an error in core Python
2/0

ZeroDivisionError: division by zero

In [14]:
# In numpy, we don't get it as an error rather it'll result in inf
mat1/0

<ipython-input-14-4a20909a461e>:1: RuntimeWarning: divide by zero encountered in true_divide
  mat1/0


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])